# -*- coding: utf-8 -*-
"""2318043 Sabastian Rafariza Wahyuono Klasifikasi Citra Natural Scenes Metode ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNxilNp3sbYR9oOL3BzGiK57q_N0BzN0

1. MOUNT GOOGLE DRIVE
"""

from google.colab import drive
drive.mount('/content/drive')

"""2. IMPORT LIBRARY"""

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from skimage.feature import graycomatrix, graycoprops
from skimage.measure import shannon_entropy

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

"""3. PATH DATASET"""

train_dir = '/content/drive/MyDrive/Colab Notebooks/Comvis/Proyek UTS/dataset/seg_train'
test_dir  = '/content/drive/MyDrive/Colab Notebooks/Comvis/Proyek UTS/dataset/seg_test'

class_mapping = {
    'buildings': 0,
    'forest': 1,
    'glacier': 2,
    'mountain': 3,
    'sea': 4,
    'street': 5
}

nama_kelas = list(class_mapping.keys())

"""4. EKSTRAKSI FITUR (SAMA STRUKTUR, LEBIH STABIL)"""

def extract_features(image_path):
    img = cv2.imread(image_path)

    if img is None:
        return None

    img = cv2.resize(img, (256, 256))

    # HSV
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    # RGB
    r, g, b = img[:,:,2], img[:,:,1], img[:,:,0]

    # Gray
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # GLCM
    glcm = graycomatrix(gray, [1], [0], 256, symmetric=True, normed=True)

    return [
        np.mean(h), np.std(h),
        np.mean(s), np.std(s),
        np.mean(r), np.mean(g), np.mean(b),
        graycoprops(glcm, 'contrast')[0,0],
        graycoprops(glcm, 'homogeneity')[0,0],
        graycoprops(glcm, 'energy')[0,0],
        graycoprops(glcm, 'correlation')[0,0],
        shannon_entropy(gray)
    ]

"""5. LOAD DATASET"""

def load_dataset(base_dir):
    data = []
    labels = []

    for folder in os.listdir(base_dir):
        folder_path = os.path.join(base_dir, folder)

        if not os.path.isdir(folder_path):
            continue

        if folder.lower() not in class_mapping:
            continue

        label = class_mapping[folder.lower()]

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg','.png','.jpeg')):
                path = os.path.join(folder_path, file)

                feat = extract_features(path)

                if feat:
                    data.append(feat)
                    labels.append(label)

    columns = [
        'mean_h','std_h','mean_s','std_s',
        'mean_r','mean_g','mean_b',
        'contrast','homogeneity','energy','correlation',
        'entropy'
    ]

    df = pd.DataFrame(data, columns=columns)
    df['label'] = labels

    return df

"""6. EKSTRAKSI DATA"""

train_df = load_dataset(train_dir)
test_df  = load_dataset(test_dir)

print("Train:", len(train_df))
print("Test :", len(test_df))

"""### 6.1 Simpan Fitur ke CSV"""

import os

# Tentukan path penyimpanan
output_dir = '/content/drive/MyDrive/Colab Notebooks/Comvis/Proyek UTS/csv'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Simpan ke CSV
train_df.to_csv(os.path.join(output_dir, 'train_features.csv'), index=False)
test_df.to_csv(os.path.join(output_dir, 'test_features.csv'), index=False)

print(f"Fitur berhasil disimpan di: {output_dir}")

"""7. SPLIT & NORMALISASI"""

X = train_df.drop('label', axis=1)
y = train_df['label']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_test = test_df.drop('label', axis=1)
y_test = test_df['label']

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

"""8. MODEL ANN"""

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),

    Dense(6, activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

"""9. TRAINING"""

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[early_stop]
)

"""10. EVALUASI"""

y_pred = np.argmax(model.predict(X_test), axis=1)

print(classification_report(y_test, y_pred, target_names=nama_kelas))

plt.figure(figsize=(8,6))
sns.heatmap(confusion_matrix(y_test, y_pred),
            annot=True, fmt='d', cmap='Blues',
            xticklabels=nama_kelas,
            yticklabels=nama_kelas)

plt.title("Confusion Matrix ANN")
plt.show()

